### PR TITLE
54 bug placed pieces do not over write

### LINKED ISSUE #54: BUG: placed pieces do not over write
When calling `place_pieces`, the old pieces on the board stay there.

### PR DESCRIPTION
**Pull request by abrahimt**

### CODE REVIEW

File: src/board.rs [hunk 1]
```diff
@@ -93,6 +93,26 @@ impl Chessboard {
         }
     }
 
+    /// Clears an instance of a chessboard.
+    ///
```
Comment (chanson02) [inline src/board.rs]: Remove empty comment line

**Review by chanson02 — APPROVED** [review]
